fix: website publish

diff --git a/.github/workflows/bench.yml b/.github/workflows/bench.yml
--- a/.github/workflows/bench.yml
+++ b/.github/workflows/bench.yml
@@ -332,7 +332,7 @@ jobs:
           node-version: 18.x
       - uses: pnpm/action-setup@v2
         with:
-          version: 8
+          version: 9
       - uses: actions/download-artifact@v3
         with:
           # Artifact name
@@ -347,8 +347,10 @@ jobs:
           pushd website
           pnpm i
           pnpm content
+          pnpm build
+          pnpm archive-dist
       - name: Site Publish
         if: github.ref == 'refs/heads/main'
         env:
           VERCEL_PUBLISH_TOKEN: ${{ secrets.VERCEL_PUBLISH_TOKEN }}
-        run: vercel website --prod --confirm -t $VERCEL_PUBLISH_TOKEN || echo 'ignore errors'
+        run: vercel website --prod --yes -t $VERCEL_PUBLISH_TOKEN || echo 'ignore errors'
