do not fail on site publish to allow build artifacts being uploaded

diff --git a/.github/workflows/bench.yml b/.github/workflows/bench.yml
--- a/.github/workflows/bench.yml
+++ b/.github/workflows/bench.yml
@@ -269,4 +269,4 @@ jobs:
         run: |
           yarn global add vercel
           export PATH="$(yarn global bin):$PATH"
-          vercel website --prod -f --with-cache -c -C -t $VERCEL_PUBLISH_TOKEN
+          vercel website --prod -c -C -t $VERCEL_PUBLISH_TOKEN || echo 'ignore errors'
